### ISSUE TITLE
JP Mining Note template render error on latest

### ISSUE THREAD

**Issue by Scrub1492** [themoeway/yomitan#437]
**Description**
The bug reproduced from https://discord.com/channels/617136488840429598/1187993478567825448.
When using the [latest JPMN handlebars](https://arbyste.github.io/jp-mining-note-prerelease/setupyomichan/#yomichan-templates), a template rendering error occurs: 
![image](https://github.com/themoeway/yomitan/assets/52880648/5fdf36a7-d1d8-4bf8-bdd1-9afdd87ea792)

When tested using the built-in tester:
![image](https://github.com/themoeway/yomitan/assets/52880648/36d6b902-607a-4ab1-8ec4-554044d1d36b)

Everything works fine when using the stable release of Yomitan. 

**Browser version**
Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Yomitan version**
Built from latest

**Exported settings file**
[yomitan-settings-2023-12-24-12-26-10.json](https://github.com/themoeway/yomitan/files/13761850/yomitan-settings-2023-12-24-12-26-10.json)

**Comment by Scrub1492** [comment]
error info dump:
```TypeError: options.fn is not a function
    at AnkiTemplateRenderer._regexMatch (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/js/templates/sandbox/anki-template-renderer.js:273:44)
    at Object.wrapper (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/js/templates/sandbox/template-renderer.js:202:20)
    at ElasticHandlebarsVisitor.invokeHelper (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:6104:30)
    at ElasticHandlebarsVisitor.processHelperNode (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:6075:12)
    at ElasticHandlebarsVisitor.processStatementOrExpression (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:5990:14)
    at ElasticHandlebarsVisitor.SubExpression (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:5923:10)
    at ElasticHandlebarsVisitor.accept (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:1996:36)
    at ElasticHandlebarsVisitor.acceptKey (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:1957:26)
    at ElasticHandlebarsVisitor.acceptArray (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:1977:16)
    at ElasticHandlebarsVisitor.resolveNodes (chrome-extension://ofdfpmhoonbdbcapcgfapibpndmhcjia/lib/handlebars.js:6302:12)```

**Comment by Scrub1492** [comment]
I believe this bug is introduced by #428 . @toasted-nutbread thoughts?

**Comment by toasted-nutbread** [comment]
For posterity, bug was introduced much earlier than #428, probably during my original type annotations change.
